name: Update Packagist

on:
  push:
    tags:
      - '*'
  create:
    tags:
      - '*'

jobs:
  packagist:
    name: Update Packagist
    runs-on: ubuntu-latest
    
    steps:
      - name: Update Packagist
        uses: php-actions/composer@v6
        with:
          command: remove
          args: --no-interaction
        env:
          PACKAGIST_TOKEN: ${{ secrets.PACKAGIST_TOKEN }}
      
      - name: Ping Packagist
        run: |
          curl -XPOST -H "Content-Type: application/json" \
            -d '{"repository":{"url":"https://github.com/${{ github.repository }}"}}' \
            "https://packagist.org/api/update-package?username=${{ secrets.PACKAGIST_USERNAME }}&apiToken=${{ secrets.PACKAGIST_TOKEN }}"